test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

s3:
  service: S3
  access_key_id:
    <%= Rails.application.credentials.dig(:s3, :access_key_id) %>
  secret_access_key:
    <%= Rails.application.credentials.dig(:s3, :secret_access_key) %>
  region: eu-central-1
  bucket: piazza-active-storage
